### ISSUE TITLE
Addin no longer compatible with latest version of Cake

### ISSUE THREAD

**Issue by DominicFarrington** [ilich/Cake.GitPackager#2]
Following error is displayed on attempting to use the package:

Error: The assembly 'Cake.GitPackager, Version=0.1.0.21894, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.17.0).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by ilich** [comment]
Please install the latest package. Thank you for your help!
